import { Product, Category } from '@/types';

export const demoCategories: Category[] = [
  { id: '1', name: 'Electronics', slug: 'electronics', icon: '💻' },
  { id: '2', name: 'Clothing', slug: 'clothing', icon: '👕' },
  { id: '3', name: 'Home & Garden', slug: 'home-garden', icon: '🏡' },
  { id: '4', name: 'Sports', slug: 'sports', icon: '⚽' },
  { id: '5', name: 'Books', slug: 'books', icon: '📚' },
  { id: '6', name: 'Beauty', slug: 'beauty', icon: '✨' },
];

export const demoProducts: Product[] = [
  {
    id: '1',
    name: 'Wireless Noise-Canceling Headphones',
    description: 'Premium over-ear headphones with active noise cancellation, 30-hour battery life, and crystal-clear audio. Perfect for music lovers and remote workers.',
    price: 299.99,
    image: '',
    category: 'Electronics',
    rating: 4.8,
    reviews_count: 1243,
    in_stock: true,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'Organic Cotton T-Shirt',
    description: 'Ultra-soft organic cotton t-shirt in a classic fit. Sustainably sourced and ethically manufactured. Available in multiple colors.',
    price: 34.99,
    image: '',
    category: 'Clothing',
    rating: 4.5,
    reviews_count: 867,
    in_stock: true,
    created_at: '2024-01-20T00:00:00Z',
  },
  {
    id: '3',
    name: 'Smart Home Security Camera',
    description: '1080p HD indoor/outdoor security camera with night vision, two-way audio, and motion detection. Works with Alexa and Google Home.',
    price: 79.99,
    image: '',
    category: 'Electronics',
    rating: 4.6,
    reviews_count: 2156,
    in_stock: true,
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'Ceramic Plant Pot Set',
    description: 'Set of 3 minimalist ceramic plant pots with drainage holes and bamboo saucers. Perfect for succulents and small indoor plants.',
    price: 42.99,
    image: '',
    category: 'Home & Garden',
    rating: 4.7,
    reviews_count: 534,
    in_stock: true,
    created_at: '2024-02-10T00:00:00Z',
  },
  {
    id: '5',
    name: 'Professional Yoga Mat',
    description: 'Extra-thick 6mm yoga mat with non-slip surface. Eco-friendly TPE material, lightweight and portable with carrying strap included.',
    price: 54.99,
    image: '',
    category: 'Sports',
    rating: 4.9,
    reviews_count: 1890,
    in_stock: true,
    created_at: '2024-02-15T00:00:00Z',
  },
  {
    id: '6',
    name: 'Bestseller Novel Collection',
    description: 'Curated collection of 5 bestselling novels from 2024. Includes hardcover editions with dust jackets. Perfect gift for book lovers.',
    price: 89.99,
    image: '',
    category: 'Books',
    rating: 4.4,
    reviews_count: 312,
    in_stock: true,
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: '7',
    name: 'Portable Bluetooth Speaker',
    description: 'Waterproof portable speaker with 360-degree sound, 20-hour battery, and built-in microphone. Compact design for adventures.',
    price: 129.99,
    image: '',
    category: 'Electronics',
    rating: 4.7,
    reviews_count: 3421,
    in_stock: true,
    created_at: '2024-03-05T00:00:00Z',
  },
  {
    id: '8',
    name: 'Natural Skincare Gift Set',
    description: 'Luxury skincare set with cleanser, toner, serum, and moisturizer. All-natural ingredients, cruelty-free, and suitable for all skin types.',
    price: 64.99,
    image: '',
    category: 'Beauty',
    rating: 4.8,
    reviews_count: 789,
    in_stock: true,
    created_at: '2024-03-10T00:00:00Z',
  },
  {
    id: '9',
    name: 'Denim Jacket — Classic Fit',
    description: 'Timeless denim jacket crafted from premium selvedge denim. Button front closure, two chest pockets, and a comfortable classic fit.',
    price: 119.99,
    image: '',
    category: 'Clothing',
    rating: 4.6,
    reviews_count: 645,
    in_stock: true,
    created_at: '2024-03-15T00:00:00Z',
  },
  {
    id: '10',
    name: 'Stainless Steel Water Bottle',
    description: 'Double-walled insulated water bottle keeps drinks cold for 24h or hot for 12h. BPA-free, leak-proof cap, 750ml capacity.',
    price: 29.99,
    image: '',
    category: 'Sports',
    rating: 4.5,
    reviews_count: 4523,
    in_stock: true,
    created_at: '2024-03-20T00:00:00Z',
  },
  {
    id: '11',
    name: 'LED Desk Lamp',
    description: 'Modern LED desk lamp with adjustable brightness, color temperature control, USB charging port, and touch controls. Energy efficient.',
    price: 49.99,
    image: '',
    category: 'Home & Garden',
    rating: 4.3,
    reviews_count: 978,
    in_stock: true,
    created_at: '2024-04-01T00:00:00Z',
  },
  {
    id: '12',
    name: 'Wireless Mechanical Keyboard',
    description: 'Compact 75% mechanical keyboard with hot-swappable switches, RGB backlighting, and Bluetooth/2.4GHz dual connectivity.',
    price: 159.99,
    image: '',
    category: 'Electronics',
    rating: 4.9,
    reviews_count: 1567,
    in_stock: false,
    created_at: '2024-04-05T00:00:00Z',
  },
];
